### PR TITLE
Support scaling

### PR DESCRIPTION
**Pull request by bofh69**
Add support for scaling to be able to draw maps like the ones in Door in the woods.

### CODE REVIEW

**Comment by bofh69** [comment]
I have modified ex09 to make use of it, but it should probably be a new example so I didn't commit it

**Comment by bofh69** [comment]
I just realized that this is lacking a center of the zoom. It can probably be handled with the offset values, but that is a hassle. Perhaps that should be added before this is merged?

**Comment by thebracket** [comment]
Giving this a look-see locally. Thank you!

**Comment by thebracket** [comment]
I like the overall effect, and it works well. So I'll merge it, and add an issue to note that there's a little more to do: the mouse position should be scaled as well.

**Pull request merged**
