### PR TITLE
HTML buttons support in WASM [WIP]

### PR DESCRIPTION
**Pull request by Zireael07**
There are several TODOs scattered across the code, in order of importance:
1) the whole setup part should be done on the game side, not library side (people can have differing HTML buttons and functions, obviously)
2) the repetitive parts should be condensed, possibly via a macro
3) the whole Command enum should be done on the game side, too, and possibly linked to the HTML button's ID
4) naming. Command is a super generic name because I didn't have a better idea and didn't remember that keys are handled via VirtualKeyCode (I had an action system in mind when coming up with this)

### CODE REVIEW

**Comment by thebracket** [comment]
I'll give this a good look in a couple of days, tied up right now. At a glance, it looks helpful - thank you!

**Comment by thebracket** [comment]
I've been through this, and it's a great start - but I think it needs to be a bit more generic. Do you mind if I take this base, credit you, and build a wider interface (it'll start in the `hal` branch; I didn't like how the platform code was intermingled with the regular code, so I've been cleaning it up)?

**Comment by Zireael07** [comment]
Feel free to take this and genericize - as I mentioned in the TODOs, most of it should be on the game's side either way.

**Comment by thebracket** [comment]
Take a look at:

* https://github.com/thebracket/rltk_rs/blob/hal/examples/ex17-wasm-external.rs
* https://github.com/thebracket/rltk_rs/blob/hal/wasm_help/index-ex17.html

That's taken the spirit of what you did, and generalized it - so you can register whatever buttons you like, and check the `ctx.web_button` for the HTML Element ID of whatever was clicked in your input loop.

**Comment by thebracket** [comment]
I'll go ahead and close this and merge in the `hal` branch. It's passing every test I can throw at it now. :-)

**Pull request closed without merging**
